[features]
seeds = false
skip-lint = false
[programs.localnet]
ona = "AsNxpqVFeND66KZCA6PFQH5pKB4TWyXykRWhUvpDkRkk"
[programs.devnet]
ona = "AsNxpqVFeND66KZCA6PFQH5pKB4TWyXykRWhUvpDkRkk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id2.json"
# wallet = "/Users/philip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
