[features]
seeds = false
skip-lint = false
[programs.localnet]
ona = "7cww21Ze4xT6nh2B7RUQ7w25zeXdf2h6DgS2M9wjU2Pp"
[programs.devnet]
ona = "7cww21Ze4xT6nh2B7RUQ7w25zeXdf2h6DgS2M9wjU2Pp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"
# wallet = "/Users/philip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
